-- ANDRES JUAN GUTIERREZ CASTRO

-- BORRAMOS LA TABLA EN CASO DE QUE YA EXISTA
DROP DATABASE IF EXISTS web_app;

-- CREAMOS LA BASE DE DATOS WEB_APP
CREATE DATABASE web_app;

-- USAMOS LA BASE DE DATOS PARA HACER LAS CONSULTAS SQL
USE web_app;

/*
LO PRIMERO DE QUE DEBE HACERSE ES DEFINIR LAS TABLAS QUE
NO CONTENGAN CLAVES FORANEAS PARA QUE NO HAYN INCONSISTENCIAS AL
MOMENTO  DE LA CREACION
*/

-- TABLAS SIN CLAVES FORANEAS
CREATE TABLE usuarios (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	usuario VARCHAR(50) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	correo VARCHAR(50) NOT NULL,
	contrasena VARCHAR(50) NOT NULL,
	estado TINYINT NOT NULL
);

CREATE TABLE catalogo (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	material VARCHAR(50) NOT NULL,
	espesor_pantalla TINYINT NOT NULL,
	diametro_cable TINYINT NOT NULL,
	ampacidad DECIMAL(5,2) NOT NULL,
	codigo_cable TINYINT NOT NULL,
	corriente TINYINT NOT NULL,
	tension INT NOT NULL
);

-- TABLAS CON LLAVES FORANEAS
CREATE TABLE proyectos (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	nombre_proyecto VARCHAR(50) NOT NULL,
	tipo_proyecto VARCHAR(50) NOT NULL,
	usuarios_id INT NOT NULL,
	FOREIGN KEY (usuarios_id) REFERENCES usuarios(id)
);

CREATE TABLE seleccion (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	nombre_seleccion VARCHAR(50) NOT NULL,
	corriente INT NOT NULL,
	tension INT NOT NULL,
	instalacion VARCHAR(50) NOT NULL,
	material VARCHAR(50) NOT NULL,
	ampacidad DECIMAL(5,2) NOT NULL,
	fecha_insercion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	usuarios_id INT NOT NULL,
	proyectos_id INT NOT NULL,
	catalogo_id INT NOT NULL,
	FOREIGN KEY (usuarios_id) REFERENCES usuarios(id),
	FOREIGN KEY (proyectos_id) REFERENCES proyectos(id),
	FOREIGN KEY (catalogo_id) REFERENCES catalogo(id)
);